version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: |
            curl -sSL https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o hadolint
            chmod +x hadolint
      - run:
          name: Lint Dockerfile
          command: |
            ./hadolint --ignore DL4005 --ignore DL3008 Dockerfile

  test:
    docker:
      - image: cimg/go:1.24.2
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v -short --count=1 $(go list ./...)

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: ./build_push_image_karsajobs.sh

workflows:
  karsajobs:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
